### ISSUE TITLE
On Mac, Preview.app reports created RTF corrupted

### ISSUE THREAD

**Issue by bedmison** [Stephen-Hamilton-C/auto-rtf#1]
**Describe the bug**
On the Mac, Preview.app is the default RTF reader. The file that is generated, while it will open in Mac Word, generates an error in Preview, saying the file is corrupted.

**To Reproduce**
1. Added script to project. 
2. Chmod'ed script +x 
3. In terminal, ./auto-rtf.py
4. Output was:
`Found project at ./
Found 1 Kotlin file
Found 2 XML files
Gathered file contents into Tutorial01.rtf. Be sure to open the file in Microsoft Word or LibreOffice Writer and print to PDF!`

[Tutorial01.rtf.zip](https://github.com/Stephen-Hamilton-C/auto-rtf/files/12578634/Tutorial01.rtf.zip)

**Screenshots**
<img width="253" alt="Screenshot 2023-09-11 at 12 56 47" src="https://github.com/Stephen-Hamilton-C/auto-rtf/assets/3663768/cf566339-14a1-49a1-8448-1c8a0b05a98c">

**Computer Specs**
 - OS: Mac 13.5.1
 - Interface: Terminal, run as shell script, with #!/usr/bin/python3 at the top.
 - Using Python 3.11.1
 - Version e.g. 1.0.2

**Comment by Stephen-Hamilton-C** [comment]
I remember reading something about some RTF readers needing more header information. I'll check it out tomorrow.

**Comment by Stephen-Hamilton-C** [comment]
Hopefully this is fixed with commit 0c4cf7a. I've sent the generated RTF file to some friends with macOS. Awaiting their responses.

And yes, I made sure to generate it with an empty Android Studio project to ensure no Honor Code violations ;)

**Comment by Stephen-Hamilton-C** [comment]
Confirmed fixes from two separate machines. I'll consider this resolved unless anyone else has issues.

Fix will be in version 1.0.3
